[[instance]]
generator_to_use = "Barabasi"
node_count = 32
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 45
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 64
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 91
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 128
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 181
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 256
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 362
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 512
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 724
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1

[[instance]]
generator_to_use = "Barabasi"
node_count = 1024
prob = 0.0
radius = 0.0
barabasi_m = 16
distribution = "Exp"
seed = 19
limit = -1
